// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GpsLocation.proto

package com.xebia.protobuf.proto;

public final class GpsLocationProtos {
  private GpsLocationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GpsLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:artel.GpsLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 latitude = 1;</code>
     */
    int getLatitude();

    /**
     * <code>sint32 longitude = 2;</code>
     */
    int getLongitude();
  }
  /**
   * Protobuf type {@code artel.GpsLocation}
   */
  public  static final class GpsLocation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:artel.GpsLocation)
      GpsLocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GpsLocation.newBuilder() to construct.
    private GpsLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GpsLocation() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GpsLocation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GpsLocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              latitude_ = input.readSInt32();
              break;
            }
            case 16: {

              longitude_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xebia.protobuf.proto.GpsLocationProtos.internal_static_artel_GpsLocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xebia.protobuf.proto.GpsLocationProtos.internal_static_artel_GpsLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.class, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private int latitude_;
    /**
     * <code>sint32 latitude = 1;</code>
     */
    public int getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private int longitude_;
    /**
     * <code>sint32 longitude = 2;</code>
     */
    public int getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0) {
        output.writeSInt32(1, latitude_);
      }
      if (longitude_ != 0) {
        output.writeSInt32(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, latitude_);
      }
      if (longitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation)) {
        return super.equals(obj);
      }
      com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation other = (com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation) obj;

      if (getLatitude()
          != other.getLatitude()) return false;
      if (getLongitude()
          != other.getLongitude()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code artel.GpsLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:artel.GpsLocation)
        com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xebia.protobuf.proto.GpsLocationProtos.internal_static_artel_GpsLocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xebia.protobuf.proto.GpsLocationProtos.internal_static_artel_GpsLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.class, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder.class);
      }

      // Construct using com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitude_ = 0;

        longitude_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xebia.protobuf.proto.GpsLocationProtos.internal_static_artel_GpsLocation_descriptor;
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation getDefaultInstanceForType() {
        return com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.getDefaultInstance();
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation build() {
        com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation buildPartial() {
        com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation result = new com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation) {
          return mergeFrom((com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation other) {
        if (other == com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.getDefaultInstance()) return this;
        if (other.getLatitude() != 0) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int latitude_ ;
      /**
       * <code>sint32 latitude = 1;</code>
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>sint32 latitude = 1;</code>
       */
      public Builder setLatitude(int value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0;
        onChanged();
        return this;
      }

      private int longitude_ ;
      /**
       * <code>sint32 longitude = 2;</code>
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>sint32 longitude = 2;</code>
       */
      public Builder setLongitude(int value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:artel.GpsLocation)
    }

    // @@protoc_insertion_point(class_scope:artel.GpsLocation)
    private static final com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation();
    }

    public static com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GpsLocation>
        PARSER = new com.google.protobuf.AbstractParser<GpsLocation>() {
      @java.lang.Override
      public GpsLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GpsLocation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GpsLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GpsLocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_artel_GpsLocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_artel_GpsLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021GpsLocation.proto\022\005artel\"2\n\013GpsLocatio" +
      "n\022\020\n\010latitude\030\001 \001(\021\022\021\n\tlongitude\030\002 \001(\021B-" +
      "\n\030com.xebia.protobuf.protoB\021GpsLocationP" +
      "rotosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_artel_GpsLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_artel_GpsLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_artel_GpsLocation_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
