// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroundData.proto

package com.xebia.protobuf.proto;

public final class GroundDataProtos {
  private GroundDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroundDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:artel.GroundData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * time in second since 1st january 1970
     * </pre>
     *
     * <code>int32 timestamp = 2;</code>
     */
    int getTimestamp();

    /**
     * <code>.artel.GpsLocation gpsLocation = 3;</code>
     */
    boolean hasGpsLocation();
    /**
     * <code>.artel.GpsLocation gpsLocation = 3;</code>
     */
    com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation getGpsLocation();
    /**
     * <code>.artel.GpsLocation gpsLocation = 3;</code>
     */
    com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder getGpsLocationOrBuilder();

    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    java.util.List<com.xebia.protobuf.proto.SensorDataProtos.SensorData> 
        getSensorDatasList();
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    com.xebia.protobuf.proto.SensorDataProtos.SensorData getSensorDatas(int index);
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    int getSensorDatasCount();
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    java.util.List<? extends com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder> 
        getSensorDatasOrBuilderList();
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder getSensorDatasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code artel.GroundData}
   */
  public  static final class GroundData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:artel.GroundData)
      GroundDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroundData.newBuilder() to construct.
    private GroundData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroundData() {
      sensorDatas_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroundData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroundData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              timestamp_ = input.readInt32();
              break;
            }
            case 26: {
              com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder subBuilder = null;
              if (gpsLocation_ != null) {
                subBuilder = gpsLocation_.toBuilder();
              }
              gpsLocation_ = input.readMessage(com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gpsLocation_);
                gpsLocation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                sensorDatas_ = new java.util.ArrayList<com.xebia.protobuf.proto.SensorDataProtos.SensorData>();
                mutable_bitField0_ |= 0x00000001;
              }
              sensorDatas_.add(
                  input.readMessage(com.xebia.protobuf.proto.SensorDataProtos.SensorData.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          sensorDatas_ = java.util.Collections.unmodifiableList(sensorDatas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xebia.protobuf.proto.GroundDataProtos.internal_static_artel_GroundData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xebia.protobuf.proto.GroundDataProtos.internal_static_artel_GroundData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xebia.protobuf.proto.GroundDataProtos.GroundData.class, com.xebia.protobuf.proto.GroundDataProtos.GroundData.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private int timestamp_;
    /**
     * <pre>
     * time in second since 1st january 1970
     * </pre>
     *
     * <code>int32 timestamp = 2;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int GPSLOCATION_FIELD_NUMBER = 3;
    private com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation gpsLocation_;
    /**
     * <code>.artel.GpsLocation gpsLocation = 3;</code>
     */
    public boolean hasGpsLocation() {
      return gpsLocation_ != null;
    }
    /**
     * <code>.artel.GpsLocation gpsLocation = 3;</code>
     */
    public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation getGpsLocation() {
      return gpsLocation_ == null ? com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.getDefaultInstance() : gpsLocation_;
    }
    /**
     * <code>.artel.GpsLocation gpsLocation = 3;</code>
     */
    public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder getGpsLocationOrBuilder() {
      return getGpsLocation();
    }

    public static final int SENSORDATAS_FIELD_NUMBER = 4;
    private java.util.List<com.xebia.protobuf.proto.SensorDataProtos.SensorData> sensorDatas_;
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    public java.util.List<com.xebia.protobuf.proto.SensorDataProtos.SensorData> getSensorDatasList() {
      return sensorDatas_;
    }
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    public java.util.List<? extends com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder> 
        getSensorDatasOrBuilderList() {
      return sensorDatas_;
    }
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    public int getSensorDatasCount() {
      return sensorDatas_.size();
    }
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    public com.xebia.protobuf.proto.SensorDataProtos.SensorData getSensorDatas(int index) {
      return sensorDatas_.get(index);
    }
    /**
     * <code>repeated .artel.SensorData sensorDatas = 4;</code>
     */
    public com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder getSensorDatasOrBuilder(
        int index) {
      return sensorDatas_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (timestamp_ != 0) {
        output.writeInt32(2, timestamp_);
      }
      if (gpsLocation_ != null) {
        output.writeMessage(3, getGpsLocation());
      }
      for (int i = 0; i < sensorDatas_.size(); i++) {
        output.writeMessage(4, sensorDatas_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (timestamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timestamp_);
      }
      if (gpsLocation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGpsLocation());
      }
      for (int i = 0; i < sensorDatas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, sensorDatas_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xebia.protobuf.proto.GroundDataProtos.GroundData)) {
        return super.equals(obj);
      }
      com.xebia.protobuf.proto.GroundDataProtos.GroundData other = (com.xebia.protobuf.proto.GroundDataProtos.GroundData) obj;

      if (getId()
          != other.getId()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (hasGpsLocation() != other.hasGpsLocation()) return false;
      if (hasGpsLocation()) {
        if (!getGpsLocation()
            .equals(other.getGpsLocation())) return false;
      }
      if (!getSensorDatasList()
          .equals(other.getSensorDatasList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp();
      if (hasGpsLocation()) {
        hash = (37 * hash) + GPSLOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getGpsLocation().hashCode();
      }
      if (getSensorDatasCount() > 0) {
        hash = (37 * hash) + SENSORDATAS_FIELD_NUMBER;
        hash = (53 * hash) + getSensorDatasList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xebia.protobuf.proto.GroundDataProtos.GroundData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code artel.GroundData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:artel.GroundData)
        com.xebia.protobuf.proto.GroundDataProtos.GroundDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xebia.protobuf.proto.GroundDataProtos.internal_static_artel_GroundData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xebia.protobuf.proto.GroundDataProtos.internal_static_artel_GroundData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xebia.protobuf.proto.GroundDataProtos.GroundData.class, com.xebia.protobuf.proto.GroundDataProtos.GroundData.Builder.class);
      }

      // Construct using com.xebia.protobuf.proto.GroundDataProtos.GroundData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSensorDatasFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        timestamp_ = 0;

        if (gpsLocationBuilder_ == null) {
          gpsLocation_ = null;
        } else {
          gpsLocation_ = null;
          gpsLocationBuilder_ = null;
        }
        if (sensorDatasBuilder_ == null) {
          sensorDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sensorDatasBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xebia.protobuf.proto.GroundDataProtos.internal_static_artel_GroundData_descriptor;
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.GroundDataProtos.GroundData getDefaultInstanceForType() {
        return com.xebia.protobuf.proto.GroundDataProtos.GroundData.getDefaultInstance();
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.GroundDataProtos.GroundData build() {
        com.xebia.protobuf.proto.GroundDataProtos.GroundData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.GroundDataProtos.GroundData buildPartial() {
        com.xebia.protobuf.proto.GroundDataProtos.GroundData result = new com.xebia.protobuf.proto.GroundDataProtos.GroundData(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.timestamp_ = timestamp_;
        if (gpsLocationBuilder_ == null) {
          result.gpsLocation_ = gpsLocation_;
        } else {
          result.gpsLocation_ = gpsLocationBuilder_.build();
        }
        if (sensorDatasBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            sensorDatas_ = java.util.Collections.unmodifiableList(sensorDatas_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sensorDatas_ = sensorDatas_;
        } else {
          result.sensorDatas_ = sensorDatasBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xebia.protobuf.proto.GroundDataProtos.GroundData) {
          return mergeFrom((com.xebia.protobuf.proto.GroundDataProtos.GroundData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xebia.protobuf.proto.GroundDataProtos.GroundData other) {
        if (other == com.xebia.protobuf.proto.GroundDataProtos.GroundData.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getTimestamp() != 0) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasGpsLocation()) {
          mergeGpsLocation(other.getGpsLocation());
        }
        if (sensorDatasBuilder_ == null) {
          if (!other.sensorDatas_.isEmpty()) {
            if (sensorDatas_.isEmpty()) {
              sensorDatas_ = other.sensorDatas_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSensorDatasIsMutable();
              sensorDatas_.addAll(other.sensorDatas_);
            }
            onChanged();
          }
        } else {
          if (!other.sensorDatas_.isEmpty()) {
            if (sensorDatasBuilder_.isEmpty()) {
              sensorDatasBuilder_.dispose();
              sensorDatasBuilder_ = null;
              sensorDatas_ = other.sensorDatas_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sensorDatasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSensorDatasFieldBuilder() : null;
            } else {
              sensorDatasBuilder_.addAllMessages(other.sensorDatas_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xebia.protobuf.proto.GroundDataProtos.GroundData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xebia.protobuf.proto.GroundDataProtos.GroundData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <pre>
       * time in second since 1st january 1970
       * </pre>
       *
       * <code>int32 timestamp = 2;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * time in second since 1st january 1970
       * </pre>
       *
       * <code>int32 timestamp = 2;</code>
       */
      public Builder setTimestamp(int value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * time in second since 1st january 1970
       * </pre>
       *
       * <code>int32 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation gpsLocation_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder> gpsLocationBuilder_;
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public boolean hasGpsLocation() {
        return gpsLocationBuilder_ != null || gpsLocation_ != null;
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation getGpsLocation() {
        if (gpsLocationBuilder_ == null) {
          return gpsLocation_ == null ? com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.getDefaultInstance() : gpsLocation_;
        } else {
          return gpsLocationBuilder_.getMessage();
        }
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public Builder setGpsLocation(com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation value) {
        if (gpsLocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gpsLocation_ = value;
          onChanged();
        } else {
          gpsLocationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public Builder setGpsLocation(
          com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder builderForValue) {
        if (gpsLocationBuilder_ == null) {
          gpsLocation_ = builderForValue.build();
          onChanged();
        } else {
          gpsLocationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public Builder mergeGpsLocation(com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation value) {
        if (gpsLocationBuilder_ == null) {
          if (gpsLocation_ != null) {
            gpsLocation_ =
              com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.newBuilder(gpsLocation_).mergeFrom(value).buildPartial();
          } else {
            gpsLocation_ = value;
          }
          onChanged();
        } else {
          gpsLocationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public Builder clearGpsLocation() {
        if (gpsLocationBuilder_ == null) {
          gpsLocation_ = null;
          onChanged();
        } else {
          gpsLocation_ = null;
          gpsLocationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder getGpsLocationBuilder() {
        
        onChanged();
        return getGpsLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      public com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder getGpsLocationOrBuilder() {
        if (gpsLocationBuilder_ != null) {
          return gpsLocationBuilder_.getMessageOrBuilder();
        } else {
          return gpsLocation_ == null ?
              com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.getDefaultInstance() : gpsLocation_;
        }
      }
      /**
       * <code>.artel.GpsLocation gpsLocation = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder> 
          getGpsLocationFieldBuilder() {
        if (gpsLocationBuilder_ == null) {
          gpsLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocation.Builder, com.xebia.protobuf.proto.GpsLocationProtos.GpsLocationOrBuilder>(
                  getGpsLocation(),
                  getParentForChildren(),
                  isClean());
          gpsLocation_ = null;
        }
        return gpsLocationBuilder_;
      }

      private java.util.List<com.xebia.protobuf.proto.SensorDataProtos.SensorData> sensorDatas_ =
        java.util.Collections.emptyList();
      private void ensureSensorDatasIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          sensorDatas_ = new java.util.ArrayList<com.xebia.protobuf.proto.SensorDataProtos.SensorData>(sensorDatas_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xebia.protobuf.proto.SensorDataProtos.SensorData, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder, com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder> sensorDatasBuilder_;

      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public java.util.List<com.xebia.protobuf.proto.SensorDataProtos.SensorData> getSensorDatasList() {
        if (sensorDatasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sensorDatas_);
        } else {
          return sensorDatasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public int getSensorDatasCount() {
        if (sensorDatasBuilder_ == null) {
          return sensorDatas_.size();
        } else {
          return sensorDatasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData getSensorDatas(int index) {
        if (sensorDatasBuilder_ == null) {
          return sensorDatas_.get(index);
        } else {
          return sensorDatasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder setSensorDatas(
          int index, com.xebia.protobuf.proto.SensorDataProtos.SensorData value) {
        if (sensorDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorDatasIsMutable();
          sensorDatas_.set(index, value);
          onChanged();
        } else {
          sensorDatasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder setSensorDatas(
          int index, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder builderForValue) {
        if (sensorDatasBuilder_ == null) {
          ensureSensorDatasIsMutable();
          sensorDatas_.set(index, builderForValue.build());
          onChanged();
        } else {
          sensorDatasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder addSensorDatas(com.xebia.protobuf.proto.SensorDataProtos.SensorData value) {
        if (sensorDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorDatasIsMutable();
          sensorDatas_.add(value);
          onChanged();
        } else {
          sensorDatasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder addSensorDatas(
          int index, com.xebia.protobuf.proto.SensorDataProtos.SensorData value) {
        if (sensorDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorDatasIsMutable();
          sensorDatas_.add(index, value);
          onChanged();
        } else {
          sensorDatasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder addSensorDatas(
          com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder builderForValue) {
        if (sensorDatasBuilder_ == null) {
          ensureSensorDatasIsMutable();
          sensorDatas_.add(builderForValue.build());
          onChanged();
        } else {
          sensorDatasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder addSensorDatas(
          int index, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder builderForValue) {
        if (sensorDatasBuilder_ == null) {
          ensureSensorDatasIsMutable();
          sensorDatas_.add(index, builderForValue.build());
          onChanged();
        } else {
          sensorDatasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder addAllSensorDatas(
          java.lang.Iterable<? extends com.xebia.protobuf.proto.SensorDataProtos.SensorData> values) {
        if (sensorDatasBuilder_ == null) {
          ensureSensorDatasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sensorDatas_);
          onChanged();
        } else {
          sensorDatasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder clearSensorDatas() {
        if (sensorDatasBuilder_ == null) {
          sensorDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sensorDatasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public Builder removeSensorDatas(int index) {
        if (sensorDatasBuilder_ == null) {
          ensureSensorDatasIsMutable();
          sensorDatas_.remove(index);
          onChanged();
        } else {
          sensorDatasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder getSensorDatasBuilder(
          int index) {
        return getSensorDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder getSensorDatasOrBuilder(
          int index) {
        if (sensorDatasBuilder_ == null) {
          return sensorDatas_.get(index);  } else {
          return sensorDatasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public java.util.List<? extends com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder> 
           getSensorDatasOrBuilderList() {
        if (sensorDatasBuilder_ != null) {
          return sensorDatasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sensorDatas_);
        }
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder addSensorDatasBuilder() {
        return getSensorDatasFieldBuilder().addBuilder(
            com.xebia.protobuf.proto.SensorDataProtos.SensorData.getDefaultInstance());
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder addSensorDatasBuilder(
          int index) {
        return getSensorDatasFieldBuilder().addBuilder(
            index, com.xebia.protobuf.proto.SensorDataProtos.SensorData.getDefaultInstance());
      }
      /**
       * <code>repeated .artel.SensorData sensorDatas = 4;</code>
       */
      public java.util.List<com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder> 
           getSensorDatasBuilderList() {
        return getSensorDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xebia.protobuf.proto.SensorDataProtos.SensorData, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder, com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder> 
          getSensorDatasFieldBuilder() {
        if (sensorDatasBuilder_ == null) {
          sensorDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.xebia.protobuf.proto.SensorDataProtos.SensorData, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder, com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder>(
                  sensorDatas_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          sensorDatas_ = null;
        }
        return sensorDatasBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:artel.GroundData)
    }

    // @@protoc_insertion_point(class_scope:artel.GroundData)
    private static final com.xebia.protobuf.proto.GroundDataProtos.GroundData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xebia.protobuf.proto.GroundDataProtos.GroundData();
    }

    public static com.xebia.protobuf.proto.GroundDataProtos.GroundData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroundData>
        PARSER = new com.google.protobuf.AbstractParser<GroundData>() {
      @java.lang.Override
      public GroundData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroundData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroundData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroundData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xebia.protobuf.proto.GroundDataProtos.GroundData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_artel_GroundData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_artel_GroundData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020GroundData.proto\022\005artel\032\021GpsLocation.p" +
      "roto\032\020SensorData.proto\"|\n\nGroundData\022\n\n\002" +
      "id\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\005\022\'\n\013gpsLocati" +
      "on\030\003 \001(\0132\022.artel.GpsLocation\022&\n\013sensorDa" +
      "tas\030\004 \003(\0132\021.artel.SensorDataB,\n\030com.xebi" +
      "a.protobuf.protoB\020GroundDataProtosb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xebia.protobuf.proto.GpsLocationProtos.getDescriptor(),
          com.xebia.protobuf.proto.SensorDataProtos.getDescriptor(),
        });
    internal_static_artel_GroundData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_artel_GroundData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_artel_GroundData_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "GpsLocation", "SensorDatas", });
    com.xebia.protobuf.proto.GpsLocationProtos.getDescriptor();
    com.xebia.protobuf.proto.SensorDataProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
