// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorData.proto

package com.xebia.protobuf.proto;

public final class SensorDataProtos {
  private SensorDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:artel.SensorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.artel.SensorData.SensorType sensorType = 1;</code>
     */
    int getSensorTypeValue();
    /**
     * <code>.artel.SensorData.SensorType sensorType = 1;</code>
     */
    com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType getSensorType();

    /**
     * <code>sint32 value = 2;</code>
     */
    int getValue();

    /**
     * <code>string additionalInfos = 3;</code>
     */
    java.lang.String getAdditionalInfos();
    /**
     * <code>string additionalInfos = 3;</code>
     */
    com.google.protobuf.ByteString
        getAdditionalInfosBytes();
  }
  /**
   * Protobuf type {@code artel.SensorData}
   */
  public  static final class SensorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:artel.SensorData)
      SensorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorData.newBuilder() to construct.
    private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorData() {
      sensorType_ = 0;
      additionalInfos_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SensorData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              sensorType_ = rawValue;
              break;
            }
            case 16: {

              value_ = input.readSInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              additionalInfos_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xebia.protobuf.proto.SensorDataProtos.internal_static_artel_SensorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xebia.protobuf.proto.SensorDataProtos.internal_static_artel_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xebia.protobuf.proto.SensorDataProtos.SensorData.class, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder.class);
    }

    /**
     * Protobuf enum {@code artel.SensorData.SensorType}
     */
    public enum SensorType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HUMIDITY = 0;</code>
       */
      HUMIDITY(0),
      /**
       * <code>TEMPERATURE = 1;</code>
       */
      TEMPERATURE(1),
      /**
       * <code>COMPACTION = 2;</code>
       */
      COMPACTION(2),
      /**
       * <code>SALINITY = 3;</code>
       */
      SALINITY(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>HUMIDITY = 0;</code>
       */
      public static final int HUMIDITY_VALUE = 0;
      /**
       * <code>TEMPERATURE = 1;</code>
       */
      public static final int TEMPERATURE_VALUE = 1;
      /**
       * <code>COMPACTION = 2;</code>
       */
      public static final int COMPACTION_VALUE = 2;
      /**
       * <code>SALINITY = 3;</code>
       */
      public static final int SALINITY_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SensorType valueOf(int value) {
        return forNumber(value);
      }

      public static SensorType forNumber(int value) {
        switch (value) {
          case 0: return HUMIDITY;
          case 1: return TEMPERATURE;
          case 2: return COMPACTION;
          case 3: return SALINITY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SensorType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SensorType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SensorType>() {
              public SensorType findValueByNumber(int number) {
                return SensorType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xebia.protobuf.proto.SensorDataProtos.SensorData.getDescriptor().getEnumTypes().get(0);
      }

      private static final SensorType[] VALUES = values();

      public static SensorType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SensorType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:artel.SensorData.SensorType)
    }

    public static final int SENSORTYPE_FIELD_NUMBER = 1;
    private int sensorType_;
    /**
     * <code>.artel.SensorData.SensorType sensorType = 1;</code>
     */
    public int getSensorTypeValue() {
      return sensorType_;
    }
    /**
     * <code>.artel.SensorData.SensorType sensorType = 1;</code>
     */
    public com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType getSensorType() {
      @SuppressWarnings("deprecation")
      com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType result = com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType.valueOf(sensorType_);
      return result == null ? com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>sint32 value = 2;</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int ADDITIONALINFOS_FIELD_NUMBER = 3;
    private volatile java.lang.Object additionalInfos_;
    /**
     * <code>string additionalInfos = 3;</code>
     */
    public java.lang.String getAdditionalInfos() {
      java.lang.Object ref = additionalInfos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        additionalInfos_ = s;
        return s;
      }
    }
    /**
     * <code>string additionalInfos = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAdditionalInfosBytes() {
      java.lang.Object ref = additionalInfos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        additionalInfos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sensorType_ != com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType.HUMIDITY.getNumber()) {
        output.writeEnum(1, sensorType_);
      }
      if (value_ != 0) {
        output.writeSInt32(2, value_);
      }
      if (!getAdditionalInfosBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, additionalInfos_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sensorType_ != com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType.HUMIDITY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, sensorType_);
      }
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, value_);
      }
      if (!getAdditionalInfosBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, additionalInfos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xebia.protobuf.proto.SensorDataProtos.SensorData)) {
        return super.equals(obj);
      }
      com.xebia.protobuf.proto.SensorDataProtos.SensorData other = (com.xebia.protobuf.proto.SensorDataProtos.SensorData) obj;

      if (sensorType_ != other.sensorType_) return false;
      if (getValue()
          != other.getValue()) return false;
      if (!getAdditionalInfos()
          .equals(other.getAdditionalInfos())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENSORTYPE_FIELD_NUMBER;
      hash = (53 * hash) + sensorType_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (37 * hash) + ADDITIONALINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getAdditionalInfos().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xebia.protobuf.proto.SensorDataProtos.SensorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code artel.SensorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:artel.SensorData)
        com.xebia.protobuf.proto.SensorDataProtos.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xebia.protobuf.proto.SensorDataProtos.internal_static_artel_SensorData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xebia.protobuf.proto.SensorDataProtos.internal_static_artel_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xebia.protobuf.proto.SensorDataProtos.SensorData.class, com.xebia.protobuf.proto.SensorDataProtos.SensorData.Builder.class);
      }

      // Construct using com.xebia.protobuf.proto.SensorDataProtos.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sensorType_ = 0;

        value_ = 0;

        additionalInfos_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xebia.protobuf.proto.SensorDataProtos.internal_static_artel_SensorData_descriptor;
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData getDefaultInstanceForType() {
        return com.xebia.protobuf.proto.SensorDataProtos.SensorData.getDefaultInstance();
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData build() {
        com.xebia.protobuf.proto.SensorDataProtos.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData buildPartial() {
        com.xebia.protobuf.proto.SensorDataProtos.SensorData result = new com.xebia.protobuf.proto.SensorDataProtos.SensorData(this);
        result.sensorType_ = sensorType_;
        result.value_ = value_;
        result.additionalInfos_ = additionalInfos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xebia.protobuf.proto.SensorDataProtos.SensorData) {
          return mergeFrom((com.xebia.protobuf.proto.SensorDataProtos.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xebia.protobuf.proto.SensorDataProtos.SensorData other) {
        if (other == com.xebia.protobuf.proto.SensorDataProtos.SensorData.getDefaultInstance()) return this;
        if (other.sensorType_ != 0) {
          setSensorTypeValue(other.getSensorTypeValue());
        }
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        if (!other.getAdditionalInfos().isEmpty()) {
          additionalInfos_ = other.additionalInfos_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xebia.protobuf.proto.SensorDataProtos.SensorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xebia.protobuf.proto.SensorDataProtos.SensorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sensorType_ = 0;
      /**
       * <code>.artel.SensorData.SensorType sensorType = 1;</code>
       */
      public int getSensorTypeValue() {
        return sensorType_;
      }
      /**
       * <code>.artel.SensorData.SensorType sensorType = 1;</code>
       */
      public Builder setSensorTypeValue(int value) {
        sensorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.artel.SensorData.SensorType sensorType = 1;</code>
       */
      public com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType getSensorType() {
        @SuppressWarnings("deprecation")
        com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType result = com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType.valueOf(sensorType_);
        return result == null ? com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType.UNRECOGNIZED : result;
      }
      /**
       * <code>.artel.SensorData.SensorType sensorType = 1;</code>
       */
      public Builder setSensorType(com.xebia.protobuf.proto.SensorDataProtos.SensorData.SensorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sensorType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.artel.SensorData.SensorType sensorType = 1;</code>
       */
      public Builder clearSensorType() {
        
        sensorType_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>sint32 value = 2;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>sint32 value = 2;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object additionalInfos_ = "";
      /**
       * <code>string additionalInfos = 3;</code>
       */
      public java.lang.String getAdditionalInfos() {
        java.lang.Object ref = additionalInfos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          additionalInfos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string additionalInfos = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAdditionalInfosBytes() {
        java.lang.Object ref = additionalInfos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          additionalInfos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string additionalInfos = 3;</code>
       */
      public Builder setAdditionalInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        additionalInfos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string additionalInfos = 3;</code>
       */
      public Builder clearAdditionalInfos() {
        
        additionalInfos_ = getDefaultInstance().getAdditionalInfos();
        onChanged();
        return this;
      }
      /**
       * <code>string additionalInfos = 3;</code>
       */
      public Builder setAdditionalInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        additionalInfos_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:artel.SensorData)
    }

    // @@protoc_insertion_point(class_scope:artel.SensorData)
    private static final com.xebia.protobuf.proto.SensorDataProtos.SensorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xebia.protobuf.proto.SensorDataProtos.SensorData();
    }

    public static com.xebia.protobuf.proto.SensorDataProtos.SensorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorData>
        PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
      @java.lang.Override
      public SensorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xebia.protobuf.proto.SensorDataProtos.SensorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_artel_SensorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_artel_SensorData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SensorData.proto\022\005artel\"\261\001\n\nSensorData" +
      "\0220\n\nsensorType\030\001 \001(\0162\034.artel.SensorData." +
      "SensorType\022\r\n\005value\030\002 \001(\021\022\027\n\017additionalI" +
      "nfos\030\003 \001(\t\"I\n\nSensorType\022\014\n\010HUMIDITY\020\000\022\017" +
      "\n\013TEMPERATURE\020\001\022\016\n\nCOMPACTION\020\002\022\014\n\010SALIN" +
      "ITY\020\003B,\n\030com.xebia.protobuf.protoB\020Senso" +
      "rDataProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_artel_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_artel_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_artel_SensorData_descriptor,
        new java.lang.String[] { "SensorType", "Value", "AdditionalInfos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
